name: RFW Manager
author: Eric Wieser

main: tk.ericwieser.rfw.RFWManager
version: 0.0.1

depend: [WorldEdit]

commands:
   team:
      description: team commands
      usage: /<command> (create|join|name|color|list)
      
   teamcreate:
      description: create a team
      usage: /<command> <name>
      permission: rfw.player  
   teamjoin:
      description: join a team
      usage: /<command> <name>
      permission: rfw.player
   teamname:
      description: rename a team
      usage: /<command> <new name>
      permission: rfw.player
   teamcolor:
      description: set the team color
      usage: /<command> <color>
      permission: rfw.player
   teamlist:
      description: list teams
      aliases: teamls
      usage: /<command>
      
   game:
      description: game commands
      usage: /<command> (start|stop|list)
      
   gamestart:
      description: start the game
      usage: /<command>
      permission: rfw.referee
   gamestop:
      description: start the game
      usage: /<command>
      permission: rfw.referee
   gamelist:
      description: list running games
      aliases: gamels
      usage: /<command>
      permission: rfw.player
      
   sumo:
      description: game commands
      usage: /<command> (define|start)
      permission: rfw.referee
      
   sumostart:
      description: try to start a sumo round
      usage: /<command>
      permission: rfw.referee
   sumodefine:
      description: start the game
      usage: /<command>
      permission: rfw.op
      
   lane:
      description: lane commands
      usage: /<command> (define|discard)
      permission: rfw.op
   lanedefine:
      description: Create a new lane or add a region to an existing one
      usage: /<command> <name>
      permission: rfw.op
   lanediscard:
      description: Discard data associated with a lane
      usage: /<command> <name>
      permission: rfw.op

      